services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: vox-app:latest
    container_name: vox-app
    restart: unless-stopped
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started
      kafka:
        condition: service_started
    ports:
      - '${APP_PORT}:8080'
    environment:
      DB_URL: postgres:5432
      REDIS_HOST: redis
      EXTERNAL_EVENT_PROVIDER: kafka
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    networks:
      - vox-network

  postgres:
    image: postgres:18-alpine
    container_name: vox-db-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres-data:/var/lib/postgresql
    ports:
      - '${POSTGRES_PORT}:5432'
    networks:
      - vox-network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}" ]
      interval: 5s
      timeout: 5s
      retries: 10

  redis:
    image: redis:7-alpine
    container_name: vox-redis
    restart: unless-stopped
    ports:
      - '${REDIS_PORT}:6379'
    networks:
      - vox-network

  kafka:
    image: apache/kafka:4.0.2
    container_name: vox-kafka
    restart: unless-stopped
    ports:
      - '${KAFKA_PORT}:9092'
      - '9094:9094'
    environment:
      CLUSTER_ID: MkU3OEVBNTcwNTJENDM2Qk

      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller

      KAFKA_LISTENERS: INTERNAL://:9092,EXTERNAL://:9094,CONTROLLER://:9093
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:9092,EXTERNAL://localhost:9094

      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093

      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
    networks:
      - vox-network

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: vox-kafka-ui
    restart: unless-stopped
    depends_on:
      kafka:
        condition: service_started
    environment:
      KAFKA_CLUSTERS_0_NAME: vox-local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092
    ports:
      - '${KAFKA_UI_PORT}:8080'
    networks:
      - vox-network

networks:
  vox-network:
    driver: bridge

volumes:
  postgres-data:
