type School {
    id: ID!
    code: String!
    name: String
    description: String
    contactPhone: String 
    contactEmail: String
    domain: String 
    address: String 
    studentCount: Int 
    isActive: Boolean
    createdAt: String 
    updatedAt: String
    classes(page: Int = 1, size: Int = 10): [SchoolClass!]
    users(page: Int = 1, size: Int = 10): [SchoolUser!]
}

type SchoolPage {
    content: [School!]!
    page: Int!
    size: Int!
    totalElements: Int!
    totalPages: Int!
}


type SchoolClass {
    id: ID!
    schoolId: ID!
    languageId: ID!
    schoolGradeId: ID!
    code: String!
    name: String!
    description: String
    status: String!
    createdAt: String
    updatedAt: String
    school: School
    schoolGrade: SchoolGrade
    language: SupportedLanguage
}

type SchoolGrade {
    id: ID!
    schoolId: ID!
    code: String
    name: String
    description: String
    startDate: String
    endDate: String
    status: String
    createdAt: String
    updatedAt: String
}

type SchoolClassPage {
    content: [SchoolClass!]!
    page: Int!
    size: Int!
    totalElements: Int!
    totalPages: Int!
}

type SchoolClassUser {
    id: ID!
    userId: ID!
    schoolClassId: ID!
    isActive: Boolean!
    joinedAt: String
    leftAt: String
    users(page: Int! = 1, size: Int! = 10): [User!]
}

type SchoolClassUserPage {
    content: [SchoolClassUser!]!
    page: Int!
    size: Int!
    totalElements: Int!
    totalPages: Int!
}

type UpdateSchoolClassResponse {
    schoolClassId: ID!
}

input UpdateSchoolClassInput {
    name: String
    description: String
    status: String
}

type UpdateSchoolUserResponse {
    schoolUserId: ID!
}

input UpdateSchoolUserInput {
    fullName: String
    phone: String
    address: String
    dateOfBirth: String
}

type SchoolUser {
    id: ID!
    schoolId: ID
    userId: ID
    startDate: String
    endDate: String
    user: User
}

type SchoolUserPage {
    content: [SchoolUser!]!
    page: Int!
    size: Int!
    totalElements: Int!
    totalPages: Int!
}

extend type Query {
    schools(page: Int = 1, size: Int = 20): SchoolPage!
    school(id: ID!): School
    schoolClasses(page: Int = 1, size: Int = 20, search: String, status: String, languageId: ID, schoolGradeId: ID): SchoolClassPage!
    schoolUsersBySchool(schoolId: ID!, page: Int! = 1, size: Int! = 20): SchoolUserPage!
    schoolUser(schoolId: ID!, userId: ID!): SchoolUser
    schoolClass(id: ID!): SchoolClass
    schoolClassUsers(schoolClassId: ID!, page: Int = 1, size: Int = 20): SchoolClassUserPage!
}

extend type Mutation {
    updateSchoolClass(id: ID!, input: UpdateSchoolClassInput!): UpdateSchoolClassResponse!
    updateSchoolUser(schoolId: ID!, userId: ID!, input: UpdateSchoolUserInput!): UpdateSchoolUserResponse!
}
