# ==================================================================
# School
# ==================================================================
type SchoolResponse {
    id: ID!
    schoolCode: String!
    name: String!
    description: String
    contactPhone: String!
    contactEmail: String!
    schoolDomain: String!
    address: String!
    studentCount: Int!
    isActive: Boolean!
    createdAt: String
    createdBy: String
    updatedAt: String
    updateBy: String
}

input UpdateSchoolRequest {
    id: ID!
    name: String
    description: String
    contactPhone: String
    contactEmail: String
    domain: String
    address: String
    studentCount: Int
}

extend type Mutation {
    updateSchool(request: UpdateSchoolRequest!): ID!
    updateSchoolRoom(input: UpdateSchoolRoomInput!): ID!
}

# ==================================================================
# School Room
# ==================================================================
type SchoolRoomResponse {
    id: ID!
    name: String!
    description: String
    isActive: Boolean!
    createdAt: String
    createdBy: String
    updatedAt: String
    updateBy: String
    schoolId: ID!
}
input UpdateSchoolRoomInput {
    id: ID!
    name: String
    description: String
    isActive: Boolean
}

type SchoolRoomPageResult {
    totalElements: Int!
    totalPages: Int!
    currentPage: Int!
    pageSize: Int!
    content: [SchoolRoomResponse!]!
}

extend type Query {
    schoolRoom(id: ID!): SchoolRoomResponse
    schoolRooms(schoolId: ID!, page: Int, size: Int): SchoolRoomPageResult
}
