enum UserRole {
    SYSTEM_ADMIN 
    SCHOOL_ADMIN 
    TEACHER 
    STUDENT
}

enum Gender {
    MALE 
    FEMALE
}

enum UserStatus {
    INACTIVE 
    ACTIVE 
    LOCKED 
    DISABLED
}

type User {
    id: ID!
    email: String!
    role: UserRole!
    phone: String
    fullName: String!
    gender: Gender 
    dateOfBirth: String 
    address: String 
    avatarUrl: String
    status: UserStatus!
    createdAt: String
    updatedAt: String
    school: School
}

type UserPage {
    content: [User!]!
    page: Int!
    size: Int!
    totalElements: Int!
    totalPages: Int!
}


extend type Query {
    users(page: Int! = 1, size: Int! = 20): UserPage!
    user(id: ID!): User
    me: User
}

input UpdateProfileInput {
    fullName: String
    phone: String
    address: String
    dateOfBirth: String
    avatarUrl: String
}

extend type Mutation {
    updateMe(input: UpdateProfileInput!): ID!
}