spring:
  application:
    name: vox

  threads:
    virtual:
      enabled: true
  graphql:
    graphiql:
      enabled: true
      
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${SMTP_USERNAME}
    password: ${SMTP_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  datasource:
    url: jdbc:postgresql://${DB_URL}/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASSWORD}

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true

springdoc:
  swagger-ui:
    path: /api-doc.html
    enabled: true
  api-docs:
    path: /v3/api-spec
  

jwt:
  secret: ${JWT_SECRET}
  expiration-ms: 1800000

logging:
  level:
    org:
      springframework:
        security: DEBUG

server:
  port: 8080
  shutdown: graceful