package com.sep.vox.domain.model.importfile;

public enum ImportType {
    USER,
    SCHOOL_CLASS,
    QUESTION,
    SCHOOL_CLASS_USER,
    SCHOOL_DIRECTORY,
    SCHOOL_GRADE_LEVEL,
    SCHOOL_GRADE,
    SCHOOL_ROOM,
    RUBRIC_VERSION,
    RUBRIC_CRITERION,
    RUBRIC_CRITERION_BAND,
    RUBRIC_RESULT_BAND,
    ASSESSMENT_POLICY
}
