package com.sep.vox.domain.model.scoringrule;

public enum ScoringRuleConditionType {
    DURATION_LESS_THAN,
    DURATION_GREATER_THAN,

    WORD_COUNT_LESS_THAN,
    WORD_COUNT_GREATER_THAN,

    CRITERION_SCORE_LESS_THAN,
    CRITERION_SCORE_GREATER_THAN,
    CRITERION_BAND_AT_OR_BELOW,
    CRITERION_BAND_AT_OR_ABOVE,

    FINAL_SCORE_LESS_THAN,
    FINAL_SCORE_GREATER_THAN,

    TASK_RELEVANCE_LESS_THAN,
    OFF_TOPIC_RATIO_GREATER_THAN,

    CODE_SWITCHING_RATIO_GREATER_THAN,

    ASR_CONFIDENCE_LESS_THAN,
    AI_CONFIDENCE_LESS_THAN,
    AUDIO_QUALITY_LESS_THAN, 

    SILENCE_RATIO_GREATER_THAN,
    SPEECH_RATE_LESS_THAN, 
    SPEECH_RATE_GREATER_THAN
}
