-- ---------------------------------------------------------------------------
-- Uu tien nhan loi: bo cua so "gan day" cung, quen theo SO LAN CHAM
--
-- Truoc day bang giu HAI con dem -- freq (cua so 60 ngay) va recent_freq (cua so
-- 14 ngay) -- roi Java chuan hoa ca hai theo cuc dai trong nhom, tron bang hai
-- trong so 0,6/0,4, cuoi cung nhan voi do yeu cua tieu chi.
--
-- Ba van de:
--
-- 1. Phep nhan voi do yeu LAT NGUOC thu tu. Do yeu tinh tu diem CAN GIUA trong
--    tung bai cham nen tong bang 0 -> khoang mot nua so tieu chi luon AM. Voi so
--    am, ORDER BY priority DESC dua nhan sai IT hon len truoc. Do tren 20.000
--    lich su ngau nhien: sai khoang 45% so lan xep thu tu.
--
-- 2. Hai cua so cung tao vach dung vo ly: loi 13 ngay tuoi tinh du 1,00 con loi
--    15 ngay chi con 0,38, du chi cach nhau 2 ngay. Va mot nhan da sua xong van
--    dung dau bang toi 60 ngay.
--
-- 3. Chuan hoa theo cuc dai trong nhom, va phep nhan do yeu, DEU LA HANG SO
--    trong pham vi so sanh that (cac nhan cua CUNG mot tieu chi -- xem
--    PracticeQuestionSelectionService.subAttributesFor, no loc theo tieu chi
--    truoc). Nen chung khong doi duoc thu tu gi, chi trang tri -- tru cai dau am
--    gay hai o muc 1.
--
-- Nay cot priority CHINH LA tong phan ra theo so lan cham da troi qua, dung lai
-- dung alpha cua EMA diem yeu ngay canh do. Khong them hang so nao.
--
-- Cot freq tho GIU LAI: no la nguong loc nhieu (minimum-sub-attribute-frequency),
-- noi "da sai 3 lan" can mot con so dem that chu khong phai mot tong phan ra.
--
-- Khong doi ten priority -> decayed_frequency: no van dung la khoa xep thu tu, va
-- doi ten keo theo entity + native query ma khong mua them duoc gi.
-- NUMERIC(6,4) van du cho: tong phan ra chan tren la (so quan sat mot lan cham)
-- x 1/(1-0,8), thuc te duoi 20, con cot chua duoc toi 99,9999.
-- ---------------------------------------------------------------------------

ALTER TABLE sub_attribute_priority DROP COLUMN recent_freq;
