create table assessment_policies (passing_score numeric(6,2) constraint chk_assessment_policies_passing_score_non_negative check (passing_score IS NULL OR passing_score >= 0), version integer not null constraint chk_assessment_policies_version_positive check (version > 0), created_at timestamp(6) with time zone not null, effective_from timestamp(6) with time zone not null, effective_to timestamp(6) with time zone, updated_at timestamp(6) with time zone not null, created_by uuid, framework_version_id uuid not null, id UUID DEFAULT uuidv7() not null, language_id uuid not null, rubric_version_id uuid not null, school_class_id uuid, school_grade_id uuid, school_grade_level_id uuid, school_id uuid, target_framework_band_id uuid not null, updated_by uuid, status varchar(20) not null constraint chk_assessment_policies_status_valid check (status IN ('DRAFT', 'PUBLISHED', 'ARCHIVED')), strictness varchar(20) not null constraint chk_assessment_policies_strictness_valid check (strictness IN ('LENIENT', 'STANDARD', 'STRICT')), primary key (id), constraint idx_assessment_policies_scope_version unique (school_id, school_grade_level_id, school_grade_id, school_class_id, language_id, framework_version_id, version), constraint chk_assessment_policies_effective_range_valid check (effective_to IS NULL OR effective_from <= effective_to));
create table device_sessions (revoked_at timestamp(6) with time zone, id UUID default uuidv7() not null, user_id uuid not null, platform varchar(20) not null constraint chk_device_sessions_platform_valid check (platform IN ('WEB', 'ANDROID', 'IOS', 'DESKTOP')), device_id varchar(255) not null, device_name varchar(255) not null, ip_address varchar(255) not null, user_agent varchar(255), primary key (id));
create table exam_appeal_reviewer_items (suggested_score numeric(5,2) not null, appeal_item_id uuid not null, appeal_reviewer_id uuid not null, evaluation_id uuid not null, id UUID DEFAULT uuidv7() not null, note varchar(2048), primary key (id), constraint uq_appeal_reviewer_item unique (appeal_reviewer_id, appeal_item_id));
create table exam_appeal_reviewers (assigned_at timestamp(6) with time zone not null, submitted_at timestamp(6) with time zone, appeal_id uuid not null, assigned_by uuid, id UUID DEFAULT uuidv7() not null, reviewer_id uuid not null, status varchar(20) not null constraint chk_exam_appeal_reviewers_status_valid check (status IN ('ASSIGNED', 'SUBMITTED')), primary key (id), constraint uq_appeal_reviewer unique (appeal_id, reviewer_id));
create table exam_blueprint_sections (section_order integer not null, section_time_limits_seconds integer, section_weight numeric(3,2) not null, created_at timestamp(6) with time zone not null, updated_at timestamp(6) with time zone not null, blueprint_version_id uuid not null, created_by uuid, id UUID DEFAULT uuidv7() not null, updated_by uuid, instruction varchar(512), title varchar(255) not null, primary key (id));
create table exam_blueprint_slots (prep_time_seconds_override integer, response_time_seconds_override integer, slot_order integer not null, weight numeric(3,2) not null, created_at timestamp(6) with time zone not null, updated_at timestamp(6) with time zone not null, blueprint_version_id uuid, created_by uuid, fixed_question_id uuid, id UUID DEFAULT uuidv7() not null, section_id uuid, updated_by uuid, slot_type varchar(20) not null constraint chk_exam_blueprint_slots_type_valid check (slot_type IN ('FIXED', 'SELECTION')), selection_spec TEXT, primary key (id));
create table exam_blueprint_versions (total_time_limit_seconds integer constraint chk_exam_blueprint_versions_total_time_limit_seconds_valid check (total_time_limit_seconds > 0), version integer not null, created_at timestamp(6) with time zone not null, effective_from timestamp(6) with time zone not null, effective_to timestamp(6) with time zone, updated_at timestamp(6) with time zone not null, blue_print_id uuid not null, created_by uuid, id UUID DEFAULT uuidv7() not null, updated_by uuid, status varchar(20) not null constraint chk_exam_blueprint_versions_status_valid check (status IN ('DRAFT', 'PUBLISHED', 'ARCHIVED')), code varchar(100) not null, description varchar(2048), primary key (id));
create table exam_blueprints (is_active boolean not null, created_at timestamp(6) with time zone not null, updated_at timestamp(6) with time zone not null, created_by uuid, id UUID DEFAULT uuidv7() not null, language_id uuid not null, school_grade_level_id uuid, school_id uuid, updated_by uuid, code varchar(100) not null, description varchar(2048), name varchar(255) not null, primary key (id));
create table exam_candidate_results (policy_version integer not null, total_score numeric(5,2), created_at timestamp(6) with time zone not null, finalized_at timestamp(6) with time zone, released_at timestamp(6) with time zone, updated_at timestamp(6) with time zone not null, assessment_policy_id uuid not null, candidate_id uuid not null, created_by uuid, exam_id uuid not null, framework_version_id uuid not null, id UUID DEFAULT uuidv7() not null, rubric_result_band_id uuid, rubric_version_id uuid not null, session_id uuid not null, target_framework_band_id uuid not null, updated_by uuid, status varchar(20) not null constraint chk_exam_candidate_results_status_valid check (status IN ('PENDING_REVIEW', 'RELEASED', 'APPEALED', 'RE_GRADING', 'FINAL', 'INVALID', 'RETAKE_REQUIRED', 'PASSED', 'FAILED')), primary key (id));
create table exam_candidates (assigned_at timestamp(6) with time zone not null, blocked_at timestamp(6) with time zone, updated_at timestamp(6) with time zone not null, assigned_by uuid, assigned_paper_id uuid, exam_id uuid not null, id UUID DEFAULT uuidv7() not null, schedule_id uuid, student_id uuid not null, updated_by uuid, status varchar(20) not null constraint chk_exam_candidates_status_valid check (status IN ('ASSIGNED', 'ATTENDED', 'ABSENT', 'COMPLETED', 'EXEMPTED', 'CANCELLED')), primary key (id), constraint uq_exam_candidates_exam_student unique (exam_id, student_id));
create table exam_grading_assignments (assigned_at timestamp(6) with time zone not null, completed_at timestamp(6) with time zone, assigned_by uuid, candidate_result_id uuid not null, id UUID DEFAULT uuidv7() not null, teacher_id uuid not null, status varchar(20) not null constraint chk_exam_grading_assignments_status_valid check (status IN ('ASSIGNED', 'COMPLETED')), primary key (id), constraint uq_grading_assignment_result unique (candidate_result_id));
create table exam_item_criterion_scores (final_score numeric(5,2) not null, raw_score numeric(5,2) not null, evaluation_id uuid not null, id UUID DEFAULT uuidv7() not null, rubric_criterion_id uuid not null, rationale varchar(512), primary key (id));
create table exam_item_evaluation_turns (asr_confidence float(53), duration_seconds integer, turn_order integer not null, word_count integer not null, evaluation_id uuid not null, id uuid not null, turn_type varchar(20) not null constraint chk_exam_item_evaluation_turns_turn_type_valid check (turn_type IN ('MAIN', 'FOLLOWUP')), audio_url TEXT not null, prompt_text TEXT, pronunciation_overall TEXT, transcript TEXT not null, word_feedback TEXT, primary key (id));
create table exam_item_evaluations (item_score numeric(5,2) not null, marked_invalid boolean not null, overall_confidence numeric(3,2), raw_item_score numeric(5,2) not null, requires_human_review boolean not null, requires_retake boolean not null, sample_count integer, evaluated_at timestamp(6) with time zone not null, id UUID DEFAULT uuidv7() not null, paper_item_id uuid not null, response_id uuid not null, reviewer_id uuid, status varchar(20) not null constraint chk_exam_item_evaluations_status_valid check (status IN ('AUTO_GRADED', 'UNDER_REVIEW', 'FINALIZED', 'SUPERSEDED')), graded_by_model varchar(100) not null, prompt_version varchar(100), review_reason_code varchar(512), engine_type varchar(255) not null constraint chk_exam_item_evaluations_engine_type_valid check (engine_type IN ('AI_SINGLE', 'AI_ENSEMBLE', 'HUMAN')), feedback_summary TEXT, signals TEXT, suggestions TEXT, validity_json TEXT, primary key (id));
create table exam_item_response_turns (duration_seconds integer, turn_order integer not null, word_count integer, answered_at timestamp(6) with time zone, created_at timestamp(6) with time zone not null, exam_item_response_id uuid not null, id uuid not null, turn_type varchar(20) constraint chk_exam_item_response_turns_turn_type_valid check (turn_type IN ('MAIN', 'FOLLOWUP')), audio_url TEXT, prompt_text TEXT, transcript TEXT, primary key (id), constraint uk_exam_item_response_turns_response_order unique (exam_item_response_id, turn_order));
create table exam_item_responses (duration_seconds integer, submitted_at timestamp(6) with time zone not null, id uuid not null, paper_item_id uuid, session_id uuid not null, audio_url varchar(4096), termination_reason TEXT, transcript TEXT, primary key (id));
create table exam_item_rule_hits (applied_order integer not null, observed_value numeric(3,2) not null, threshold numeric(3,2) not null, created_at timestamp(6) with time zone not null, created_by uuid, evaluation_id uuid not null, id UUID DEFAULT uuidv7() not null, scoring_rule_id uuid not null, severity varchar(20) not null constraint chk_exam_item_rule_hits_severity_status check (severity IN ('INFO', 'WARNING', 'BLOCKING')), effect_summary varchar(512) not null, action_type TEXT not null, condition_type TEXT not null, reason_code varchar(255) not null, rule_code varchar(255) not null, primary key (id));
create table exam_members (granted_at timestamp(6) with time zone not null, exam_id uuid not null, granted_by uuid, id UUID DEFAULT uuidv7() not null, user_id uuid not null, role varchar(20) not null constraint role check (role IN ('CHAIR', 'AUTHOR', 'REVIEWER')), primary key (id));
create table exam_paper_items (item_order integer not null, weight numeric(5,2) not null, blueprint_slot_id uuid, id UUID DEFAULT uuidv7() not null, paper_id uuid, question_id uuid, section_id uuid, primary key (id));
create table exam_paper_sections (section_order integer not null, section_time_limit_seconds integer, weight numeric(8,4), created_at timestamp(6) with time zone not null, updated_at timestamp(6) with time zone not null, created_by uuid, id UUID DEFAULT uuidv7() not null, paper_id uuid not null, updated_by uuid, title varchar(1024) not null, instruction varchar(2048), primary key (id));
create table exam_papers (time_duration_seconds integer, variant integer not null, created_at timestamp(6) with time zone not null, updated_at timestamp(6) with time zone not null, blueprint_version_id uuid, created_by uuid, exam_id uuid not null, id UUID DEFAULT uuidv7() not null, updated_by uuid, status varchar(20) not null constraint chk_exam_papers_status_valid check (status IN ('DRAFT', 'IN_REVIEW', 'APPROVED', 'LOCKED')), code varchar(100) not null, primary key (id));
create table exam_recordings (duration_seconds integer, assembled_at timestamp(6) with time zone, created_at timestamp(6) with time zone not null, size_bytes bigint, candidate_id uuid not null, exam_session_id uuid not null, id UUID DEFAULT uuidv7() not null, status varchar(20) not null constraint chk_exam_recordings_status_valid check (status IN ('PROCESSING', 'READY', 'PARTIAL', 'FAILED', 'ABANDONED')), stream_type varchar(20) not null constraint chk_exam_recordings_stream_type_valid check (stream_type IN ('SCREEN', 'CAMERA')), source varchar(32), s3_key varchar(1024) not null, bucket varchar(2048) not null, primary key (id), constraint uq_exam_recordings_session_stream_source unique (exam_session_id, stream_type, source));
create table exam_result_appeal_items (final_score numeric(5,2), appeal_id uuid not null, id UUID DEFAULT uuidv7() not null, paper_item_id uuid not null, response_id uuid not null, primary key (id), constraint uq_appeal_item unique (appeal_id, paper_item_id));
create table exam_result_appeals (score_after numeric(5,2), score_before numeric(5,2), approved_at timestamp(6) with time zone, deadline timestamp(6) with time zone, requested_at timestamp(6) with time zone not null, resolved_at timestamp(6) with time zone, candidate_result_id uuid not null, id UUID DEFAULT uuidv7() not null, requested_by uuid not null, resolved_by uuid, status varchar(20) not null constraint chk_exam_result_appeals_status_valid check (status IN ('PENDING', 'APPROVED', 'GRADING', 'COMPARING', 'PUBLISHED', 'REJECTED')), decision_note varchar(512), notes varchar(512), reason varchar(512) not null, primary key (id));
create table exam_schedule_proctors (id UUID DEFAULT uuidv7() not null, schedule_id uuid not null, teacher_id uuid not null, primary key (id), constraint exam_schedule_proctors_schedule_teacher unique (schedule_id, teacher_id));
create table exam_schedules (created_at timestamp(6) with time zone not null, end_date timestamp(6) with time zone not null, start_date timestamp(6) with time zone not null, updated_at timestamp(6) with time zone not null, created_by uuid, exam_id uuid not null, id UUID DEFAULT uuidv7() not null, moved_to_schedule_id uuid, school_room_id uuid, updated_by uuid, status varchar(20) not null constraint chk_exam_schedules_status_valid check (status IN ('DRAFT', 'PUBLISHED', 'COMPLETED', 'MOVED', 'CANCELLED', 'DELETED')), primary key (id));
create table exam_secure_pools (created_at timestamp(6) with time zone not null, embargo_until timestamp(6) with time zone, released_at timestamp(6) with time zone, updated_at timestamp(6) with time zone not null, created_by uuid, exam_id uuid not null, id UUID DEFAULT uuidv7() not null, released_by uuid, updated_by uuid, release_mode varchar(20) not null constraint chk_exam_secure_pools_release_mode_valid check (release_mode IN ('MANUAL', 'AUTO_AFTER_CLOSE')), status varchar(20) not null constraint chk_exam_secure_pools_status_valid check (status IN ('SEALED', 'RELEASED')), primary key (id));
create table exam_sessions (flagged boolean not null, remaining_seconds integer, started_at timestamp(6) with time zone not null, submitted_at timestamp(6) with time zone, candidate_id uuid not null, exam_id uuid not null, id UUID DEFAULT uuidv7() not null, paper_id uuid not null, chosen_stream_type varchar(20) constraint chk_exam_sessions_chosen_stream_type_valid check (chosen_stream_type IN ('CAMERA', 'SCREEN', 'CAMERA_AND_SCREEN')), status varchar(20) not null constraint chk_exam_sessions_status_valid check (status IN ('IN_PROGRESS', 'SUBMITTED', 'INTERRUPTED', 'GRADING', 'GRADED', 'EXPIRED', 'GRADING_FAILED')), flag_reason text, primary key (id));
create table exams (exam_time_duration_second integer, max_attempt integer, requires_otp BOOLEAN NOT NULL DEFAULT true not null, close_at timestamp(6) with time zone, created_at timestamp(6) with time zone not null, open_at timestamp(6) with time zone, updated_at timestamp(6) with time zone not null, assessment_policy_id uuid, blueprint_id uuid, blueprint_version_id uuid, created_by uuid, id UUID DEFAULT uuidv7() not null, language_id uuid not null, school_id uuid, updated_by uuid, delivery_mode varchar(20) constraint chk_exams_delivery_mode_valid check (delivery_mode IN ('STUDENT_DEVICE', 'LAB')), kind varchar(20) not null constraint chk_exams_kind_valid check (kind IN ('CENTRALIZED', 'CLASS_TEST')), required_stream_type varchar(20) constraint chk_exams_required_stream_type_valid check (required_stream_type IN ('CAMERA', 'SCREEN', 'CAMERA_AND_SCREEN')), result_decision_method varchar(20) constraint chk_exams_result_decision_method_valid check (result_decision_method IN ('HIGHEST', 'LATEST', 'AVERAGE', 'FIRST', 'LOWEST')), status varchar(20) not null constraint chk_exams_status_valid check (status IN ('DRAFT', 'SCHEDULED', 'IN_PROGRESS', 'CLOSED', 'RESULTS_PUBLISHED', 'CANCELLED')), stream_type_permission varchar(20) constraint chk_exams_stream_type_permission_valid check (stream_type_permission IN ('ANY', 'ALL')), code varchar(100) not null, description varchar(2048), name varchar(255) not null, primary key (id), constraint chk_exams_required_stream_type_and_stream_type_permission_valid check (    (
        required_stream_type IS NULL
        AND stream_type_permission IS NULL
    )
    OR
    (
        required_stream_type = 'CAMERA_AND_SCREEN'
        AND stream_type_permission IN ('ANY', 'ALL')
    )
    OR
    (
        required_stream_type IN ('CAMERA', 'SCREEN')
        AND stream_type_permission IS NULL
    )
));
create table financial_event (amount_signed numeric(15,0) not null, currency varchar(3) not null, occurred_at timestamp(6) with time zone not null, actor_id uuid, id UUID DEFAULT uuidv7() not null, school_id uuid not null, subscription_id uuid, payment_method varchar(20) not null constraint chk_financial_event_payment_method_valid check (payment_method IN ('PAYOS', 'MANUAL')), event_type varchar(30) not null constraint chk_financial_event_event_type_valid check (event_type IN ('SUB_PURCHASED', 'SUB_RENEWED', 'SUB_CANCELLED', 'SUB_UPGRADED', 'TOKEN_PURCHASED', 'TOKEN_CONSUMED', 'REFUND_ISSUED')), payload TEXT, primary key (id));
create table framework_criteria (criteria_order integer not null, created_at timestamp(6) with time zone not null, updated_at timestamp(6) with time zone not null, created_by uuid, framework_version_id uuid not null, id UUID DEFAULT uuidv7() not null, updated_by uuid, code varchar(50) not null, description varchar(2048), name varchar(255) not null, primary key (id), constraint idx_framework_criteria_version_code unique (framework_version_id, code));
create table framework_criterion_bands (created_at timestamp(6) with time zone not null, updated_at timestamp(6) with time zone not null, created_by uuid, framework_criterion_id uuid not null, framework_result_band_id uuid not null, id UUID DEFAULT uuidv7() not null, updated_by uuid, descriptor TEXT, negative_signals_json TEXT, positive_signals_json TEXT, primary key (id), constraint idx_framework_criterion_bands_criterion_result unique (framework_criterion_id, framework_result_band_id));
create table framework_result_bands (result_band_order integer not null, created_at timestamp(6) with time zone not null, updated_at timestamp(6) with time zone not null, created_by uuid, framework_version_id uuid not null, id UUID DEFAULT uuidv7() not null, updated_by uuid, code varchar(50) not null, label varchar(100) not null, description varchar(2048), primary key (id), constraint idx_framework_result_bands_version_code unique (framework_version_id, code), constraint idx_framework_result_bands_version_label unique (framework_version_id, label));
create table framework_versions (version integer not null constraint chk_framework_versions_version_positive check (version > 0), created_at timestamp(6) with time zone not null, effective_from timestamp(6) with time zone not null, effective_to timestamp(6) with time zone, updated_at timestamp(6) with time zone not null, created_by uuid, framework_id uuid not null, id UUID DEFAULT uuidv7() not null, updated_by uuid, status varchar(20) not null constraint chk_framework_versions_status_valid check (status IN ('DRAFT', 'PUBLISHED', 'ARCHIVED')), code varchar(100) not null, description varchar(2048), name varchar(255) not null, primary key (id), constraint idx_framework_versions_framework_version unique (framework_id, version), constraint idx_framework_versions_framework_code unique (framework_id, code), constraint chk_framework_versions_effective_range_valid check (effective_to IS NULL OR effective_from <= effective_to));
create table frameworks (is_active boolean not null, created_at timestamp(6) with time zone not null, updated_at timestamp(6) with time zone not null, created_by uuid, id UUID DEFAULT uuidv7() not null, updated_by uuid, code varchar(50) not null, description varchar(2048), name varchar(255) not null, primary key (id), constraint idx_frameworks_code unique (code));
create table import_rows (row_number bigint not null constraint chk_import_rows_row_number_positive check (row_number > 0), id UUID DEFAULT uuidv7() not null, session_id uuid not null, status varchar(30) not null constraint chk_import_rows_status_valid check (status IN ('PENDING', 'VALID', 'INVALID', 'IMPORTED', 'SKIPPED', 'FAILED')), errors_json TEXT, mapped_data_json TEXT, raw_data_json TEXT not null, primary key (id), constraint idx_import_rows_session_row_number unique (session_id, row_number));
create table import_sessions (attempts integer not null, claimed_at timestamp(6) with time zone, created_at timestamp(6) with time zone not null, expires_at timestamp(6) with time zone not null, imported_rows bigint not null, invalid_rows bigint not null, lease_expires_at timestamp(6) with time zone, skipped_rows bigint not null, total_rows bigint not null, updated_at timestamp(6) with time zone not null, valid_rows bigint not null, claimed_by uuid, created_by uuid not null, id UUID DEFAULT uuidv7() not null, imported_entity_id uuid, school_id uuid, updated_by uuid not null, status varchar(30) not null constraint chk_import_sessions_status_valid check (status IN ('PREVIEWED', 'VALIDATING', 'IMPORTING', 'QUEUED', 'COMPLETED', 'FAILED', 'EXPIRED', 'CANCELLED')), type varchar(30) not null constraint chk_import_sessions_type_valid check (type IN ('USER', 'SCHOOL_CLASS', 'SCHOOL_CLASS_USER','QUESTION', 'SCHOOL_DIRECTORY', 'SCHOOL_GRADE_LEVEL', 'SCHOOL_GRADE','RUBRIC_VERSION','RUBRIC_CRITERION','ASSESSMENT_POLICY')), confirmed_mapping_json TEXT, failure_reason TEXT, file_name varchar(255) not null, original_headers_json TEXT not null, suggested_mapping_json TEXT, primary key (id), constraint chk_import_sessions_row_counts_non_negative check (valid_rows >= 0 AND invalid_rows >= 0 AND imported_rows >= 0 AND skipped_rows >= 0 AND total_rows >= 0));
create table invoice (amount numeric(15,0) not null, issue_date date not null, paid_at timestamp(6) with time zone, payos_order_code bigint unique, id UUID DEFAULT uuidv7() not null, school_id uuid not null, source_id uuid not null, subscription_id uuid, source_type varchar(20) not null constraint chk_invoice_source_type_valid check (source_type IN ('SUBSCRIPTION', 'SUBSCRIPTION_REQUEST', 'TOKEN_PURCHASE')), status varchar(20) not null constraint chk_invoice_status_valid check (status IN ('PAID', 'PENDING', 'FAILED', 'CANCELLED')), checkout_url varchar(2048), invoice_number varchar(255) not null unique, payment_link_id varchar(255), primary key (id));
create table outboxes (retry_count integer not null, created_at timestamp(6) with time zone not null, next_retry_at timestamp(6) with time zone, published_at timestamp(6) with time zone, aggregate_id uuid not null, id UUID DEFAULT uuidv7() not null, status varchar(20) not null constraint chk_outboxs_status_valid check (status IN ('PENDING', 'PROCESSING', 'PUBLISHED', 'FAILED')), aggregate_type varchar(100) not null, event_type varchar(150) not null, last_error TEXT, payload JSONB, primary key (id));
create table password_set_up_tokens (created_at timestamp(6) with time zone not null, expired_at timestamp(6) with time zone not null, used_at timestamp(6) with time zone, id UUID DEFAULT uuidv7() not null, user_id uuid not null, token_hash varchar(255) not null, primary key (id));
create table plan_quota (included_quantity integer not null, token_unit_price numeric(15,0) not null, id UUID DEFAULT uuidv7() not null, plan_id uuid not null, quota_type varchar(20) not null constraint chk_plan_quota_quota_type_valid check (quota_type IN ('GRADING', 'CLASS_TEST', 'PRACTICE')), primary key (id));
create table processed_events (processed_at timestamp(6) with time zone not null, event_id uuid not null, id UUID DEFAULT uuidv7() not null, consumer_group varchar(255) not null, primary key (id), constraint idx_processed_events_event_consumer_group unique (event_id, consumer_group));
create table question_assets (duration_seconds integer, question_asset_order integer not null, id UUID DEFAULT uuidv7() not null, question_id uuid not null, type varchar(100) not null constraint chk_question_assets_type_valid check (type IN ('AUDIO', 'IMAGE', 'VIDEO', 'TEXT_PASSAGE')), description varchar(2048), url varchar(4096), alt_text varchar(255), title varchar(255), transcript TEXT, primary key (id), constraint uk_question_assets_question_id unique (question_id), constraint idx_question_assets_question_question_asset_order unique (question_id, question_asset_order));
create table question_bank_grades (attached_at timestamp(6) with time zone not null, attached_by uuid, id UUID DEFAULT uuidv7() not null, question_bank_id uuid not null, school_grade_id uuid not null, primary key (id), constraint idx_question_bank_grades_bank_grade unique (question_bank_id, school_grade_id));
create table question_banks (created_at timestamp(6) with time zone not null, updated_at timestamp(6) with time zone not null, created_by uuid, id UUID DEFAULT uuidv7() not null, language_id uuid not null, school_id uuid, updated_by uuid, owner_type varchar(20) not null constraint chk_question_banks_owner_type_valid check (owner_type IN ('SYSTEM', 'SCHOOL')), code varchar(100) not null, description varchar(2048), name varchar(255) not null, status varchar(255) not null constraint chk_quesion_banks_status_valid check (status IN ('DRAFT', 'PUBLISHED', 'ARCHIVED')), primary key (id), constraint idx_question_banks_language_school_code unique (owner_type, language_id, school_id, code), constraint chk_owner_type_and_school_id_valid check ((
    owner_type = 'SYSTEM' AND school_id IS NULL
)
OR
(
    owner_type = 'SCHOOL' AND school_id IS NOT NULL
)
));
create table question_collaborators (assigned_at timestamp(6) with time zone not null, id UUID DEFAULT uuidv7() not null, question_id uuid not null, user_id uuid not null, permission varchar(20) not null constraint chk_question_collaborators_permission_valid check (permission IN ('READ_ONLY', 'CAN_USE', 'CAN_EDIT')), primary key (id), constraint idx_question_collaborators_question_user unique (question_id, user_id));
create table question_evaluation_guides (id UUID DEFAULT uuidv7() not null, question_id uuid not null, acceptable_responses TEXT, common_mistakes TEXT, expected_content TEXT, key_points TEXT, off_topic_examples TEXT, scoring_hints TEXT, primary key (id), constraint idx_question_evaluation_guides_question unique (question_id));
create table question_topics (created_at timestamp(6) with time zone not null, updated_at timestamp(6) with time zone not null, created_by uuid, id UUID DEFAULT uuidv7() not null, question_bank_id uuid not null, updated_by uuid, status varchar(20) not null constraint chk_question_topics_status_valid check (status IN ('DRAFT', 'PUBLISHED', 'ARCHIVED')), code varchar(100) not null, description varchar(2048), name varchar(255) not null, primary key (id), constraint idx_question_topics_question_bank_code unique (question_bank_id, code));
create table questions (locked boolean not null, max_response_seconds integer not null constraint chk_questions_max_response_seconds_valid check (max_response_seconds >= 0), min_response_seconds integer not null constraint chk_questions_min_response_seconds_valid check (min_response_seconds >= 0), preparation_time_seconds integer not null constraint chk_questions_preparation_time_seconds_valid check (preparation_time_seconds >= 0), created_at timestamp(6) with time zone not null, updated_at timestamp(6) with time zone not null, created_by uuid, id UUID DEFAULT uuidv7() not null, question_bank_id uuid not null, question_topic_id uuid, secure_pool_id uuid, source_question_id uuid, updated_by uuid, confidentiality varchar(20) not null constraint chk_questions_confidentiality_valid check (confidentiality IN ('OPEN', 'EXAM_RESTRICTED', 'RELEASED')), type varchar(50) not null constraint chk_questions_type_valid check (type IN ('READ_ALOUD', 'SHORT_ANSWER', 'LONG_ANSWER', 'OPINION', 'DESCRIPTION')), code varchar(100) not null, sharing varchar(100) constraint chk_questions_sharing_valid check (sharing IN ('PRIVATE', 'SCHOOL_SHARED')), instruction_text TEXT, preparation_text TEXT, prompt_text TEXT, question_text TEXT not null, status varchar(255) not null constraint chk_status_valid check (status IN ('DRAFT', 'SUBMITTED_FOR_REVIEW', 'REVISION_REQUESTED', 'APPROVED', 'REJECTED', 'PUBLISHED', 'ARCHIVED')), primary key (id), constraint idx_questions_question_topic_code unique (question_topic_id, code), constraint chk_questions_min_response_seconds_and_max_response_seconds_valid check (min_response_seconds <= max_response_seconds));
create table refresh_tokens (expired_at timestamp(6) with time zone not null, issued_at timestamp(6) with time zone not null, used_at timestamp(6) with time zone, id UUID DEFAULT uuidv7() not null, replaced_by uuid, session_id uuid not null, token_hash varchar(512) not null, primary key (id), constraint idx_refresh_token_hash unique (token_hash));
create table register_form_documents (created_at timestamp(6) with time zone not null, id UUID DEFAULT uuidv7() not null, register_form_id uuid not null, url varchar(4096) not null, primary key (id));
create table register_forms (date_of_birth date not null, student_count integer not null, created_at timestamp(6) with time zone not null, updated_at timestamp(6) with time zone not null, verified_at timestamp(6) with time zone, postal_code varchar(10) not null, id UUID default uuidv7() not null, reviewed_by uuid, school_directory_id uuid, contact_phone varchar(20) not null, identity_number varchar(20) not null, status varchar(20) not null constraint chk_register_forms_status_valid check (status IN ('PENDING', 'AUTO_APPROVED', 'APPROVED', 'REJECTED')), verification_method varchar(20) not null constraint chk_register_form_verification_method_valid check (verification_method IN ('DOMAIN_OTP', 'DOCUMENT')), position varchar(50) not null, school_domain varchar(100), contact_address varchar(512) not null, school_address varchar(512), contact_email varchar(255) not null, contact_full_name varchar(255) not null, rejected_reason varchar(255), school_district varchar(255), school_name varchar(255), school_province varchar(255), primary key (id));
create table roles (created_at timestamp(6) with time zone not null, updated_at timestamp(6) with time zone not null, created_by uuid, id UUID DEFAULT uuidv7() not null, updated_by uuid, code varchar(100) not null, name varchar(255) not null, primary key (id), constraint idx_role_code unique (code));
create table rubric_criterions (criterion_order integer not null constraint chk_rubric_criterions_order_positive check (criterion_order > 0), is_required boolean not null, max_score numeric(6,2) not null, min_score numeric(6,2) not null, weight numeric(6,2) not null constraint chk_rubric_criterions_weight_non_negative check (weight >= 0), created_at timestamp(6) with time zone not null, updated_at timestamp(6) with time zone not null, created_by uuid, framework_criterion_id uuid not null, id UUID DEFAULT uuidv7() not null, rubric_version_id uuid not null, updated_by uuid, code varchar(50) not null, description varchar(2048), examples_json TEXT, name varchar(255) not null, primary key (id), constraint idx_rubric_criterions_version_code unique (rubric_version_id, code), constraint idx_rubric_criterions_version_framework_criterion unique (rubric_version_id, framework_criterion_id), constraint chk_rubric_criterions_score_range_valid check (min_score <= max_score));
create table rubric_result_bands (result_order integer not null constraint chk_rubric_result_bands_order_valid check (result_order > 0), score_max numeric(6,2) not null, score_min numeric(6,2) not null, created_at timestamp(6) with time zone not null, updated_at timestamp(6) with time zone not null, created_by uuid, id UUID DEFAULT uuidv7() not null, rubric_version_id uuid not null, updated_by uuid, description varchar(2048), code varchar(255) not null, name varchar(255) not null, primary key (id), constraint idx_rubric_result_bands_version_id_code unique (rubric_version_id, code), constraint chk_rubric_result_bands_score_min_max_valid check (score_min <= score_max));
create table rubric_versions (scoring_scale_max numeric(6,2) not null, scoring_scale_min numeric(6,2) not null, version integer not null constraint chk_rubric_versions_version_positive check (version > 0), created_at timestamp(6) with time zone not null, effective_from timestamp(6) with time zone not null, effective_to timestamp(6) with time zone, updated_at timestamp(6) with time zone not null, created_by uuid, id UUID DEFAULT uuidv7() not null, rubric_id uuid not null, updated_by uuid, status varchar(20) not null constraint chk_rubric_versions_status_valid check (status IN ('DRAFT', 'PUBLISHED', 'ARCHIVED')), total_score_method varchar(30) not null constraint chk_rubric_versions_total_score_method_valid check (total_score_method IN ('WEIGHTED_AVERAGE', 'SUM')), code varchar(100) not null, description varchar(2048), name varchar(255) not null, primary key (id), constraint idx_rubric_versions_rubric_id_code unique (rubric_id, code), constraint idx_rubric_versions_rubric_id_version unique (rubric_id, version), constraint chk_rubric_versions_scoring_scale_valid check (scoring_scale_min <= scoring_scale_max), constraint chk_rubric_versions_effective_range_valid check (effective_to IS NULL OR effective_from <= effective_to));
create table rubrics (framework_id uuid not null, id UUID DEFAULT uuidv7() not null, language_id uuid not null, school_id uuid, owner_type varchar(20) not null constraint chk_rubrics_owner_type_valid check (owner_type IN ('SYSTEM', 'SCHOOL')), code varchar(50) not null, description varchar(2048), name varchar(255) not null, primary key (id), constraint idx_rubrics_owner_scope_code unique (owner_type, school_id, language_id, framework_id, code), constraint chk_rubrics_owner_school_valid check ((owner_type = 'SYSTEM' AND school_id IS NULL) OR (owner_type = 'SCHOOL' AND school_id IS NOT NULL)));
create table school_class_users (is_active boolean not null, joined_at timestamp(6) with time zone not null, left_at timestamp(6) with time zone, assigned_by uuid not null, id UUID DEFAULT uuidv7() not null, school_class_id uuid not null, user_id uuid not null, primary key (id), constraint idx_school_class_users unique (user_id, school_class_id));
create table school_classes (created_at timestamp(6) with time zone not null, updated_at timestamp(6) with time zone not null, created_by uuid not null, id UUID DEFAULT uuidv7() not null, language_id uuid not null, school_grade_id uuid not null, school_id uuid not null, updated_by uuid not null, status varchar(20) not null constraint chk_school_class_status_valid check (status IN ('INACTIVE', 'ACTIVE', 'ARCHIVED')), code varchar(100) not null, description varchar(2048), name varchar(255) not null, primary key (id), constraint idx_school_class_code unique (school_id, code), constraint idx_school_class_class_school_language unique (id, school_id, language_id));
create table school_directories (verified boolean not null, created_at timestamp(6) with time zone not null, updated_at timestamp(6) with time zone not null, created_by uuid, id UUID DEFAULT uuidv7() not null, updated_by uuid, source varchar(30) not null constraint chk_school_directories_source_valid check (source IN ('OFFICIAL_IMPORT', 'ADMIN_CREATED', 'USER_SUBMITTED')), code varchar(100) not null, domain varchar(100), province_code varchar(100) not null, address varchar(512) not null, district_name varchar(255) not null, name varchar(255) not null, province_name varchar(255) not null, primary key (id), constraint idx_school_directories_code unique (code));
create table school_grade_levels (grade_level_order integer not null constraint chk_school_grade_levels_order_positive check (grade_level_order > 0), created_at timestamp(6) with time zone not null, updated_at timestamp(6) with time zone not null, created_by uuid, id UUID DEFAULT uuidv7() not null, school_id uuid not null, updated_by uuid, status varchar(20) not null constraint chk_school_grade_levels_status_valid check (status IN ('ACTIVE', 'INACTIVE')), code varchar(100) not null, description varchar(2048), name varchar(255) not null, primary key (id), constraint idx_school_grade_levels_school_code unique (school_id, code), constraint idx_school_grade_levels_school_order unique (school_id, grade_level_order));
create table school_grades (end_date date not null, start_date date not null, created_at timestamp(6) with time zone not null, updated_at timestamp(6) with time zone not null, created_by uuid, id UUID DEFAULT uuidv7() not null, school_grade_level_id uuid not null, updated_by uuid, status varchar(20) not null constraint chk_status_valid check (status IN ('INACTIVE', 'ACTIVE', 'ARCHIVED')), code varchar(100) not null, description varchar(2048), name varchar(255) not null, primary key (id), constraint idx_school_grades_level_code unique (school_grade_level_id, code), constraint chk_school_grades_start_end_date_valid check (start_date < end_date));
create table school_rooms (is_active boolean not null, created_at timestamp(6) with time zone not null, updated_at timestamp(6) with time zone not null, created_by uuid, id UUID DEFAULT uuidv7() not null, school_id uuid not null, updated_by uuid, code varchar(50) not null, description varchar(2048), name varchar(255) not null, primary key (id), constraint school_rooms_school_code unique (school_id, code));
create table school_subscription (end_date date not null, price_paid_snapshot numeric(15,0) not null, start_date date not null, cancelled_at timestamp(6) with time zone, created_at timestamp(6) with time zone not null, id UUID DEFAULT uuidv7() not null, plan_id uuid not null, school_id uuid not null, status varchar(20) not null constraint chk_school_subscription_status_valid check (status IN ('ACTIVE', 'EXPIRED', 'CANCELLED')), primary key (id));
create table school_users (end_date timestamp(6) with time zone, start_date timestamp(6) with time zone not null, id UUID DEFAULT uuidv7() not null, school_id uuid not null, user_id uuid not null, primary key (id), constraint idx_school_users_user unique (user_id), constraint idx_school_users_school_user unique (school_id, user_id), constraint chk_school_users_start_date_and_end_date_valid check (start_date < end_date));
create table schools (is_active boolean not null, student_count integer not null constraint chk_student_count_positive check (student_count > 0), created_at timestamp(6) with time zone not null, updated_at timestamp(6) with time zone not null, created_by uuid not null, id UUID DEFAULT uuidv7() not null, updated_by uuid not null, contact_phone varchar(20) not null, code varchar(100) not null, domain varchar(100), address varchar(512) not null, description varchar(2048), contact_email varchar(255) not null, name varchar(255) not null, primary key (id), constraint idx_schools_code unique (code), constraint idx_schools_code_domain unique (code, domain));
create table scoring_rules (is_active boolean not null, priority integer not null constraint chk_scoring_rules_priority_positive check (priority > 0), stop_processing boolean not null, created_at timestamp(6) with time zone not null, updated_at timestamp(6) with time zone not null, created_by uuid, id UUID DEFAULT uuidv7() not null, policy_id uuid not null, updated_by uuid, severity varchar(20) not null constraint chk_scoring_rules_severity_valid check (severity IN ('INFO', 'WARNING', 'BLOCKING')), action_type varchar(50) not null constraint chk_scoring_rules_action_type_valid check (action_type IN ('CAP_FINAL_SCORE', 'CAP_CRITERION_SCORE', 'ADD_FINAL_SCORE_DELTA', 'ADD_CRITERION_SCORE_DELTA', 'CAP_FRAMEWORK_RESULT_BAND', 'SET_FRAMEWORK_RESULT_BAND', 'REQUIRE_HUMAN_REVIEW', 'MARK_RESPONSE_INVALID', 'REQUIRE_RETAKE', 'ADD_FEEDBACK_TAG', 'ADD_REVIEW_REASON')), code varchar(50) not null, condition_type varchar(50) not null constraint chk_scoring_rules_condition_type_valid check (condition_type IN ('DURATION_LESS_THAN', 'DURATION_GREATER_THAN', 'WORD_COUNT_LESS_THAN', 'WORD_COUNT_GREATER_THAN', 'CRITERION_SCORE_LESS_THAN', 'CRITERION_SCORE_GREATER_THAN', 'FINAL_SCORE_LESS_THAN', 'FINAL_SCORE_GREATER_THAN', 'TASK_RELEVANCE_LESS_THAN', 'OFF_TOPIC_RATIO_GREATER_THAN', 'CODE_SWITCHING_RATIO_GREATER_THAN', 'ASR_CONFIDENCE_LESS_THAN', 'AI_CONFIDENCE_LESS_THAN', 'AUDIO_QUALITY_LESS_THAN', 'SILENCE_RATIO_GREATER_THAN', 'SPEECH_RATE_LESS_THAN', 'SPEECH_RATE_GREATER_THAN')), description varchar(2048), action_params_json TEXT not null, condition_params_json TEXT not null, name varchar(255) not null, primary key (id), constraint idx_scoring_rules_policy_code unique (policy_id, code));
create table subscription_plan (is_popular boolean not null, max_student_count integer not null, max_time_per_attempt_min integer not null, price_per_year numeric(15,0) not null, validity_days integer not null, version integer not null, created_at timestamp(6) with time zone not null, created_by uuid, id UUID DEFAULT uuidv7() not null, status varchar(20) not null constraint chk_subscription_plan_status_valid check (status IN ('ACTIVE', 'ARCHIVED')), name varchar(255) not null, tagline varchar(255), primary key (id));
create table subscription_quota (total_allocated integer not null, used_quantity integer not null, id UUID DEFAULT uuidv7() not null, subscription_id uuid not null, quota_type varchar(20) not null constraint chk_subscription_quota_quota_type_valid check (quota_type IN ('GRADING', 'CLASS_TEST', 'PRACTICE')), primary key (id));
create table subscription_request (amount numeric(15,0) not null, reviewed_at timestamp(6) with time zone, submitted_at timestamp(6) with time zone not null, current_plan_id uuid, id UUID DEFAULT uuidv7() not null, requested_plan_id uuid not null, reviewed_by uuid, school_id uuid not null, request_type varchar(20) not null constraint chk_subscription_request_request_type_valid check (request_type IN ('REGISTRATION', 'UPGRADE')), status varchar(20) not null constraint chk_subscription_request_status_valid check (status IN ('PENDING', 'APPROVED', 'REJECTED')), primary key (id));
create table supported_languages (is_active boolean not null, created_at timestamp(6) with time zone not null, updated_at timestamp(6) with time zone not null, code varchar(10) not null, created_by uuid, id UUID DEFAULT uuidv7() not null, updated_by uuid, name varchar(100) not null, description varchar(2048), primary key (id), constraint idx_language_code unique (code));
create table token_purchase (total_amount numeric(15,0) not null, purchased_at timestamp(6) with time zone not null, id UUID DEFAULT uuidv7() not null, subscription_id uuid not null, status varchar(20) not null constraint chk_token_purchase_status_valid check (status IN ('PENDING', 'PAID', 'FAILED')), primary key (id));
create table token_purchase_item (quantity integer not null, subtotal numeric(15,0) not null, unit_price_snapshot numeric(15,0) not null, id UUID DEFAULT uuidv7() not null, purchase_id uuid not null, quota_type varchar(20) not null constraint chk_token_purchase_item_quota_type_valid check (quota_type IN ('GRADING', 'CLASS_TEST', 'PRACTICE')), primary key (id));
create table token_usage_event (tokens_consumed integer not null, occurred_at timestamp(6) with time zone not null, exam_session_id uuid not null, id UUID DEFAULT uuidv7() not null, subscription_id uuid not null, quota_type varchar(20) not null constraint chk_token_usage_event_quota_type_valid check (quota_type IN ('GRADING', 'CLASS_TEST', 'PRACTICE')), primary key (id));
create table user_roles (created_at timestamp(6) with time zone not null, id UUID DEFAULT uuidv7() not null, role_id uuid not null, user_id uuid not null, primary key (id), constraint idx_user_roles unique (user_id, role_id));
create table users (date_of_birth date not null, created_at timestamp(6) with time zone not null, updated_at timestamp(6) with time zone not null, gender varchar(15), created_by uuid, id UUID DEFAULT uuidv7() not null, updated_by uuid, phone varchar(20), status varchar(20) not null constraint chk_users_status_valid check (status IN ('ACTIVE', 'INACTIVE', 'LOCKED', 'DISABLED')), avatar_url varchar(4096), address varchar(255), email varchar(255) not null, full_name varchar(255) not null, password_hash varchar(255) not null, primary key (id), constraint idx_user_email unique (email), constraint idx_user_phone unique (phone));
create index idx_assessment_policies_grade_status on assessment_policies (school_id, school_grade_level_id, school_grade_id, language_id, framework_version_id, status);
create index idx_assessment_policies_rubric_version on assessment_policies (rubric_version_id);
create index idx_assessment_policies_target_band on assessment_policies (target_framework_band_id);
create index idx_device_sessions_users on device_sessions (user_id);
create index idx_appeal_reviewer_items_reviewer on exam_appeal_reviewer_items (appeal_reviewer_id);
create index idx_appeal_reviewers_reviewer_status on exam_appeal_reviewers (reviewer_id, status);
create index idx_grading_assignments_teacher_status on exam_grading_assignments (teacher_id, status);
create index idx_exam_item_response_turns_response on exam_item_response_turns (exam_item_response_id);
create index idx_exam_item_response_turns_response_order on exam_item_response_turns (exam_item_response_id, turn_order);
create index idx_exam_result_appeal_items_appeal on exam_result_appeal_items (appeal_id);
create index idx_exam_result_appeals_candidate_result on exam_result_appeals (candidate_result_id);
create index idx_exam_result_appeals_status on exam_result_appeals (status);
create index idx_framework_criterion_bands_result on framework_criterion_bands (framework_result_band_id);
create index idx_framework_versions_status on framework_versions (status);
create index idx_frameworks_active on frameworks (is_active);
create index idx_import_rows_session_status on import_rows (session_id, status);
create index idx_import_sessions_school_type_status on import_sessions (school_id, type, status);
create index idx_import_sessions_school_created_at on import_sessions (school_id, created_at);
create index idx_import_sessions_expires_at on import_sessions (expires_at);
create index idx_invoice_school on invoice (school_id);
create index idx_outboxes_pending on outboxes (status, next_retry_at, created_at);
create index idx_password_user_token on password_set_up_tokens (user_id, token_hash);
create index idx_question_assets_question on question_assets (question_id);
create index idx_question_bank_grades_school_grade on question_bank_grades (school_grade_id);
create index idx_question_collaborators_user on question_collaborators (user_id);
create index idx_questions_type on questions (type);
create index idx_questions_sharing on questions (sharing);
create index idx_questions_source_question on questions (source_question_id);
create index idx_refresh_token_sessions on refresh_tokens (session_id);
create index idx_register_form_documents_register_form on register_form_documents (register_form_id);
create index idx_register_identity on register_forms (identity_number);
create index idx_register_phone on register_forms (contact_phone);
create index idx_register_email on register_forms (contact_email);
create index idx_role_name on roles (name);
create index idx_rubric_criterions_framework_criterion on rubric_criterions (framework_criterion_id);
create index idx_rubric_versions_status on rubric_versions (status);
create index idx_rubrics_language_framework on rubrics (language_id, framework_id);
create index idx_school_class_users_user_id on school_class_users (user_id);
create index idx_school_class_name on school_classes (school_id, name);
create index idx_school_grades_level on school_grades (school_grade_level_id);
create index idx_schools_name on schools (name);
create index idx_scoring_rules_policy_priority on scoring_rules (policy_id, priority);
create index idx_scoring_rules_policy_active on scoring_rules (policy_id, is_active);
create index idx_language_name on supported_languages (name);
create index idx_user_roles_role_id on user_roles (role_id);
